#!/bin/bash
# Deployment Script - Interactive walkthrough for Vercel + Railway

echo "=========================================="
echo "Teladoc Express - Automated Deployment"
echo "=========================================="
echo ""

# Step 1: Railway Deployment
echo "📦 STEP 1: Deploy ML Service to Railway"
echo "---"
echo "A browser window will open. Follow these steps:"
echo ""
echo "1. Sign in with GitHub"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose: kolananish/cornell_health_ai"
echo "5. Click 'Deploy'"
echo "6. Wait 5-10 minutes for build to complete"
echo ""
read -p "Press ENTER when Railway deployment is complete..."

echo ""
echo "Getting Railway service URL..."
echo ""
read -p "Paste your Railway public URL (e.g., https://teladoc-ml-service-prod.railway.app): " RAILWAY_URL

# Step 2: Vercel Deployment
echo ""
echo "🚀 STEP 2: Deploy Frontend to Vercel"
echo "---"
echo "A browser window will open. Follow these steps:"
echo ""
echo "1. Sign in with GitHub"
echo "2. Click 'Add New' → 'Project'"
echo "3. Select 'Import Git Repository'"
echo "4. Choose: kolananish/cornell_health_ai"
echo "5. Click 'Import'"
echo "6. Wait 2-3 minutes for build to complete"
echo ""
read -p "Press ENTER when Vercel deployment is complete..."

# Step 3: Environment Variables
echo ""
echo "🔗 STEP 3: Connect Services"
echo "---"
echo "Now setting environment variables in Vercel..."
echo ""
echo "In your Vercel Dashboard:"
echo "1. Go to Settings → Environment Variables"
echo "2. Add new variable:"
echo "   Name: ML_SERVICE_URL"
echo "   Value: $RAILWAY_URL"
echo "3. Click Save"
echo "4. Click 'Redeploy'"
echo ""
read -p "Press ENTER when you've set the environment variable and redeployed..."

# Step 4: Testing
echo ""
echo "✅ STEP 4: Testing"
echo "---"
echo "Your app should now be live!"
echo ""
echo "Test the frontend:"
echo "1. Open your Vercel deployment URL"
echo "2. You should see the medical history form"
echo ""
echo "Test the API connection:"
echo "1. Open browser DevTools (F12)"
echo "2. Go to Console tab"
echo "3. Paste:"
echo "   fetch('/api/model/healthz').then(r => r.json()).then(console.log)"
echo "4. Press Enter"
echo "5. Should see: { status: 'ready', model_name: '...', ... }"
echo ""

echo "=========================================="
echo "✨ Deployment Complete!"
echo "=========================================="
echo ""
echo "Your application is now live!"
echo ""
echo "Next steps:"
echo "1. Test voice recording at /voice-recording"
echo "2. Monitor logs in Vercel and Railway dashboards"
echo "3. Set up custom domain (optional)"
echo ""
